// wasm.ts — the "wasm" backend: the simdrng C ABI compiled to a single WASM
// module (wasm_glue.cpp + simdrng_c_static under emcc), driven through the
// Emscripten runtime. Works in the browser and under Node.
//
// Bulk fills marshal across the WASM heap: malloc a buffer, call the C fill,
// copy the result out (always before _free, and re-reading the heap view each
// time since growth invalidates it). The 64-bit seed is passed as two 32-bit
// halves to sr_create_split to avoid i64 in ccall.

import type { Backend, BackendGenerator } from "./backend.js";

type CFn = (...args: number[]) => number;

interface WasmModule {
  _malloc: CFn;
  _free: (ptr: number) => void;
  _simdrng_fill_double: CFn;
  _simdrng_fill_u64: CFn;
  _simdrng_get_kind: CFn;
  _simdrng_free: CFn;
  _sr_create_split: CFn;
  HEAPU8: Uint8Array;
  HEAPF64: Float64Array;
  ccall(name: string, returnType: string | null, argTypes: string[], args: unknown[]): unknown;
  [key: string]: unknown;
}

const U32 = 0xffffffffn;

class WasmGenerator implements BackendGenerator {
  readonly kind: number;
  constructor(
    private readonly M: WasmModule,
    private handle: number,
  ) {
    this.kind = M._simdrng_get_kind(handle);
  }

  random(n: number): Float64Array {
    const M = this.M;
    const ptr = M._malloc(n * 8);
    M._simdrng_fill_double(this.handle, ptr, n);
    // Copy out of the heap before freeing; re-view in case the heap grew.
    const out = new Float64Array(M.HEAPF64.buffer, ptr, n).slice();
    M._free(ptr);
    return out;
  }

  raw(n: number): BigUint64Array {
    const M = this.M;
    const ptr = M._malloc(n * 8);
    M._simdrng_fill_u64(this.handle, ptr, n);
    const out = new BigUint64Array(M.HEAPU8.buffer, ptr, n).slice();
    M._free(ptr);
    return out;
  }

  free(): void {
    if (this.handle) {
      this.M._simdrng_free(this.handle);
      this.handle = 0;
    }
  }
}

export async function makeWasmBackend(): Promise<Backend> {
  // The .mjs glue is generated by emcc into dist/. Build a runtime URL so tsc
  // does not try to resolve the not-yet-existing module.
  const url = new URL("./simdrng.mjs", import.meta.url).href;
  const mod = (await import(url)) as { default: (opts?: unknown) => Promise<WasmModule> };
  const M = await mod.default();
  const versionString = M.ccall("simdrng_version", "string", [], []) as string;
  return {
    name: "wasm",
    versionString,
    create(kind: number, seed: bigint): BackendGenerator {
      const hi = Number((seed >> 32n) & U32);
      const lo = Number(seed & U32);
      const handle = M._sr_create_split(kind, hi, lo);
      if (handle === 0) {
        const msg = M.ccall("simdrng_last_error", "string", [], []) as string;
        throw new Error(msg || "simdrng_create returned NULL");
      }
      return new WasmGenerator(M, handle);
    },
  };
}
