include(CheckCXXCompilerFlag)
include(CheckLinkerFlag)

function(add_compile_flags_if_supported OUTVAR)
    foreach (flag ${ARGN})
        string(MAKE_C_IDENTIFIER "HAS_${flag}" var)
        check_cxx_compiler_flag("${flag}" ${var})
        if (${var})
            list(APPEND ${OUTVAR} "${flag}")
        endif ()
    endforeach ()
    set(${OUTVAR} "${${OUTVAR}}" PARENT_SCOPE)
endfunction()

function(add_link_flags_if_supported OUTVAR)
    foreach (flag ${ARGN})
        string(MAKE_C_IDENTIFIER "HAS_LNK_${flag}" var)
        check_linker_flag(CXX "${flag}" ${var})
        if (${var})
            list(APPEND ${OUTVAR} "${flag}")
        endif ()
    endforeach ()
    set(${OUTVAR} "${${OUTVAR}}" PARENT_SCOPE)
endfunction()
